package framework

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/opeteer/ace/internal/config"
)

// ScaffoldDjango generates a standard, production-ready Django 5 project structure
func ScaffoldDjango(cfg *config.ProjectConfig) error {
	base := cfg.TargetPath

	// Python package name must use underscores
	pkgName := pythonPackageName(cfg.Name)

	dirs := []string{
		pkgName,
		"static",
		"templates",
		"tests",
	}

	for _, d := range dirs {
		if err := os.MkdirAll(filepath.Join(base, d), 0755); err != nil {
			return err
		}
	}

	secretKey := generateDjangoSecretKey()

	files := map[string]string{
		"manage.py": fmt.Sprintf(`#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys

def main():
    """Run administrative tasks."""
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', '%s.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)

if __name__ == '__main__':
    main()
`, pkgName),

		"requirements.txt": `Django>=5.0,<5.2
psycopg[binary]>=3.1.0
python-dotenv>=1.0.0
gunicorn>=22.0.0
`,

		"pyproject.toml": fmt.Sprintf(`[project]
name = "%s"
version = "0.1.0"
description = "Scaffolded with Ace CLI"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "Django>=5.0,<5.2",
    "psycopg[binary]>=3.1.0",
    "python-dotenv>=1.0.0",
    "gunicorn>=22.0.0",
]
`, cfg.Name),

		filepath.Join(pkgName, "__init__.py"): ``,

		filepath.Join(pkgName, "settings.py"): fmt.Sprintf(`"""
Django settings for %s project.
Generated by Ace CLI.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('SECRET_KEY', '%s')
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '*').split(',') if h.strip()]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '%s.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '%s.wsgi.application'
ASGI_APPLICATION = '%s.asgi.application'

# Database configuration
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.sqlite3')
if 'postgres' in DB_ENGINE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', '%s'),
            'USER': os.getenv('DB_USER', 'ace_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'secret'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
elif 'mysql' in DB_ENGINE or 'mariadb' in DB_ENGINE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME', os.getenv('MYSQL_DATABASE', 'ace_db')),
            'USER': os.getenv('DB_USER', 'ace_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'secret'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
`, cfg.Name, secretKey, pkgName, pkgName, pkgName, cfg.DBName()),

		filepath.Join(pkgName, "urls.py"): fmt.Sprintf(`"""
URL configuration for %s project.
"""
from django.contrib import admin
from django.urls import path
from %s import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('api/health/', views.health, name='health'),
]
`, cfg.Name, pkgName),

		filepath.Join(pkgName, "views.py"): fmt.Sprintf(`from django.http import JsonResponse
from datetime import datetime, timezone

def index(request):
    return JsonResponse({
        "app": "%s",
        "framework": "Django 5",
        "status": "online",
        "scaffolded_by": "Ace CLI",
    })

def health(request):
    return JsonResponse({
        "status": "healthy",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    })
`, cfg.Name),

		filepath.Join(pkgName, "wsgi.py"): fmt.Sprintf(`"""
WSGI config for %s project.
"""
import os
from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '%s.settings')

application = get_wsgi_application()
`, cfg.Name, pkgName),

		filepath.Join(pkgName, "asgi.py"): fmt.Sprintf(`"""
ASGI config for %s project.
"""
import os
from django.core.asgi import get_asgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '%s.settings')

application = get_asgi_application()
`, cfg.Name, pkgName),

		"tests/__init__.py": ``,

		"tests/test_views.py": fmt.Sprintf(`from django.test import TestCase, Client

class ViewTestCase(TestCase):
    def setUp(self):
        self.client = Client()

    def test_index_view(self):
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)
        self.assertJSONEqual(
            str(response.content, encoding='utf8'),
            {
                "app": "%s",
                "framework": "Django 5",
                "status": "online",
                "scaffolded_by": "Ace CLI",
            }
        )

    def test_health_view(self):
        response = self.client.get('/api/health/')
        self.assertEqual(response.status_code, 200)
        self.assertIn("status", response.json())
`, cfg.Name),

		".gitignore": `*.pyc
__pycache__/
*.sqlite3
.env
.venv/
env/
venv/
staticfiles/
media/
.pytest_cache/
.coverage
htmlcov/
`,

		".env.example": fmt.Sprintf(`SECRET_KEY=%s
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
DB_ENGINE=django.db.backends.sqlite3
DB_NAME=db.sqlite3
`, secretKey),
	}

	for relPath, content := range files {
		targetFile := filepath.Join(base, relPath)
		_ = os.MkdirAll(filepath.Dir(targetFile), 0755)
		if err := os.WriteFile(targetFile, []byte(content), 0644); err != nil {
			return err
		}
	}

	// Make manage.py executable
	_ = os.Chmod(filepath.Join(base, "manage.py"), 0755)

	// Create initial .env from .env.example
	envExample, err := os.ReadFile(filepath.Join(base, ".env.example"))
	if err == nil {
		_ = os.WriteFile(filepath.Join(base, ".env"), envExample, 0644)
	}

	return nil
}

func pythonPackageName(name string) string {
	s := strings.ToLower(name)
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteRune('_')
		}
	}
	res := strings.Trim(b.String(), "_")
	if res == "" || (res[0] >= '0' && res[0] <= '9') {
		return "app_" + res
	}
	return res
}

func generateDjangoSecretKey() string {
	b := make([]byte, 32)
	_, _ = rand.Read(b)
	return "django-insecure-" + hex.EncodeToString(b)
}
